### ISSUE TITLE
duckdb v1.1.3: IO Error: Failed to install remote extension "protobuf" from url "https://duckdb.0xcaff.xyz/v1.1.3/linux_amd64_gcc4/protobuf.duckdb_extension"

### ISSUE THREAD

**Issue by cpatulea** [0xcaff/duckdb_protobuf#27]
```
$ duckdb
v1.1.3 19864453f7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D INSTALL protobuf from 'https://duckdb.0xcaff.xyz';
IO Error: Failed to install remote extension "protobuf" from url "https://duckdb.0xcaff.xyz/v1.1.3/linux_amd64_gcc4/protobuf.duckdb_extension"
D
```

same with unsigned
```
$ duckdb -unsigned
v1.1.3 19864453f7
Enter ".help" for usage hints.
D INSTALL protobuf from 'https://duckdb.0xcaff.xyz';
IO Error: Failed to install remote extension "protobuf" from url "https://duckdb.0xcaff.xyz/v1.1.3/linux_amd64_gcc4/protobuf.duckdb_extension"
```

**Comment by 0xcaff** [comment]
hey! I don't yet have builds hosted for duckdb v1.1.3 yet, the latest version of duckdb_protobuf should be compatible with the latest duckdb. follow the `install from file` section in the readme for now and I'll wire something up to automatically redirect requests from new versions of duckdb to the latest build

thanks for flagging

**Comment by hongbo-miao** [comment]
Met same error, it would be great to support v1.1.3, thank you! ☺️

**Comment by 0xcaff** [comment]
To be clear, 1.1.3 is supported, the auto installer just doesn't know how to install it. Try the workaround.

**Comment by 0xcaff** [comment]
try again now, I setup a redirection based on duckdb version which maps to the highest supported api version. this should work now

```
INSTALL protobuf from 'https://duckdb.0xcaff.xyz';
```

**Comment by hongbo-miao** [comment]
Thank you, I can confirm the new published version works well! 🎉
