### ISSUE TITLE
can not load on win64 platform.

### ISSUE THREAD

**Issue by david-shu** [0xcaff/duckdb_protobuf#6]
hi,

i compiled it on win64 platform and i got a duckdb_protobuf.dll.

libduckdb downloaded from 'https://github.com/duckdb/duckdb/releases/download/v1.0.0/libduckdb-windows-amd64.zip',

then followed by the guide on 'https://github.com/duckdb/duckdb-rs':

When linking against a DuckDB library already on the system (so not using any of the bundled features), you can set the DUCKDB_LIB_DIR environment variable to point to a directory containing the library. You can also set the DUCKDB_INCLUDE_DIR variable to point to the directory containing duckdb.h.

cargo build --release

duckdb_protobuf.dll got.

run:

duckdb --unsigned
load 'e:/x/duckdb_protobuf.dll';

raised

"The file is not a DuckDB extension. The metadata at the end of the file is invalid"

**Comment by 0xcaff** [comment]
hey hey, we just changed some stuff to get things working with duckdb 1.0.0, taking a look now

**Comment by 0xcaff** [comment]
I've setup builds for windows, it should publish a release under tag [v0.0.3](https://github.com/0xcaff/duckdb_protobuf/releases/tag/v0.0.3) in about 10m once the build completes. Here's the link to the current build status.

https://github.com/0xcaff/duckdb_protobuf/actions/runs/10052393429/job/27783495002

**Comment by 0xcaff** [comment]
just validated in a windows vm that downloading the file from release and loading it works. give it a go and if there's something unexpected please reopen
